version: "2.1"
volumes:
  fin:
services:
  finabler:
    restart: always
    image: localhost:5000/finabler:latest
    network_mode: host
    privileged: true
    volumes:
      - "fin:/data/firmware"
    labels:
      io.balena.features.supervisor-api: "1"
      io.balena.features.balena-api: "1"
    expose:
      - "1337"
