version: '2.1'
volumes:
    fin:
services:
  finblock:
    restart: always
    image: balenablocks/finabler:latest
    privileged: true
    network_mode: "host"
    volumes:
      - 'fin:/data/firmware'
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RAWIO
    labels:
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
      io.balena.features.sysfs: '1'
      io.balena.features.kernel-modules: '1'
    environment:
    - "DEBUG=firmata,flasher,downloader,supervisor,eeprom,main"
    - "AUTOFLASH=1"
    - "AUTOCONFIG=1"
    expose:
      - "1337"